package com.KoutalayaAdminEmp.model;

import jakarta.persistence.*;

@Entity // Marks this class as a JPA entity
@Table(name = "koutalya_admin")
public class AdminModel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generated by MySQL
    private Long id;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(name = "id_card_number", nullable = false, unique = true)
    private String idCardNumber;

    public AdminModel() {
    }

    public AdminModel(String email, String idCardNumber) {
        this.email = email;
        this.idCardNumber = idCardNumber;
    }

    // getters & setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getIdCardNumber() {
        return idCardNumber;
    }

    public void setIdCardNumber(String idCardNumber) {
        this.idCardNumber = idCardNumber;
    }
}
